export const FETCH_MANIFEST = 'FETCH_MANIFEST';

export const STORE_MANIFEST_STATUS = 'STORE_MANIFEST_STATUS';

export const STORE_WEAPON = 'STORE_WEAPON';
export const STORE_PERKS = 'STORE_PERKS';
export const STORE_MOD = 'STORE_MOD';
export const STORE_MW = 'STORE_MW';

export const STORE_RARITY = 'STORE_RARITY';
export const STORE_WEAPON_TYPE = 'STORE_WEAPON_TYPE';
export const STORE_DAMAGE = 'STORE_DAMAGE';

export const STORE_COMPARISON_WEAPON_ONE = 'STORE_COMPARISON_WEAPON_ONE';
export const STORE_COMPARISON_WEAPON_TWO = 'STORE_COMPARISON_WEAPON_TWO';